blockfrost/blockfrost-backend-ryo

README.md

I've found we are lacking a `BLOCKFROST_CONFIG_DBSYNC_PASSWORD` environment variable, which basically means we are relying on the postgres client library to use `PGPASSWORD` to provide a password.
I guess this was on purpose to prevent people committing passwords to config files, so I've just added a oneliner as heads up just in case people wonder how they'd se this up.

docs(README): add some basic details on how the postgres auth works

---

README.md
config/development-testnet.ts
config/development.ts
config/mainnet.ts
config/test.ts
config/testnet.ts
src/config.ts
src/server.ts

In order to run within docker, we need to allow fastify to listen in any given address (`0.0.0.0`). This PR adds an environment variable for that and some basic doco around it.

feat(fastify): introduced $BLOCKFROST_CONFIG_SERVER_LISTEN_ADDRESS

---

CHANGELOG.md
src/routes/network/eras.ts
src/types/queries/scripts.ts
src/utils/common.ts
src/utils/string-utils.ts
test/integration/fixtures/mainnet/addresses.ts
test/integration/tests/mainnet/network.integration.ts
test/unit/fixtures/network.fixtures.ts

is `current epoch + 2` only when we are in the safe zone (`current slot
in epoch >= epoch length - safe zone`) where hardfork can no longer occur.
Otherwise it is `current epoch + 1`.

fix(network/eras): latest epoch boundary 

---

README.md

Upstream doesn't want these so adding them to docs with the rest of our custom ones.
Related to #42.

docs: add more custom indices

---

src/routes/addresses/address/extended.ts
src/routes/assets/asset/index.ts

`getMetadataFromOutputDatum` can throw an error if datum cbor is not valid (eg. malformed hex or there could be a bug in parsing lib).

fix(cip68): catch errors caused by invalid datum

---

CHANGELOG.md
default.nix

This change makes the memory monitored by pm2 configurable by env variables.

feat(nix): configurable memory for pm2

---

Dockerfile
README.md

nix: add missing -ryo suffix

---

CHANGELOG.md
src/sql/scripts/scripts_datum_datum_hash_cbor.sql

Fixed to have a similar behavior as `/scripts/datum/{datum-hash}` endpoint that looks into both tables correctly when querying `JSON` value.

fix(scripts): `/scripts/datum/{datum-hash}/cbor` returns redeemer CBOR too

---

README.md
default.nix
flake.lock
flake.nix
nixos-module.nix

It seems to work but I haven't tested it more than `curl`ing `/health` for now, will follow updates if it doesn't work.
This assumes that whoever uses this module also enable `postgres`, `cardano-node` and `cardano-db-sync`. To do so I've used their NixOS modules (respectively from [nixpkgs](https://github.com/NixOS/nixpkgs), [cardano-node](https://github.com/input-output-hk/cardano-node) and [https://github.com/input-output-hk/cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync)). I've copy/pasted a more agnostic version of my config in the README, however it's just an idea of how to use it, many parts are just comments.
It would have been possible also providing a more opinionated module where one can simply set something like `services.easy-blockfrost.enable = true` and …

NixOS module

---

CHANGELOG.md
README.md
src/app.ts
src/config.ts

Adds support for optionally defining a Postgres password. The alternative to checking if the config has the value would be to consider an empty string `''` or `nil` as no password. Let me know if this would be preferable

feat: support postgres password

---

.github/workflows/CI.yaml
.gitlab-ci.yml
CHANGELOG.md
default.nix
flake.nix
nixos-module.nix
shell.nix

Addresses couple of minor issues
- PostgreSQL port defaults to `5432`
- `HOME` directory
- Sets package default
Additionally makes our integration tests use the module so it gets tested on PRs.
cc @aciceri

NixOS module tweaks

---

CHANGELOG.md
src/app.ts

Adds a missing route registration for the `/prometheus` endpoint and includes the relevant changelog entry.

fix: enable prometheus endpoint

---

CHANGELOG.md
README.md

Indices improving performance of queries not covered by vanilla dbsync, namely;
`/assets/{asset}` when querying CIP68 assets
`/txs/{tx_hash}` with redeemers

docs(sql): add new indices

---

CHANGELOG.md
src/sql/assets/assets_asset_transactions.sql
src/sql/assets/assets_asset_txs.sql
src/sql/epochs/epochs_number_stakes.sql

Fixes https://github.com/blockfrost/blockfrost-backend-ryo/issues/144
When using `sorted_limited` improvement, data needs to be re-ordered by id in the outer select as well, to maintain fixed ordering at all times.

fix(sql): ordering where sorted_limited is used

---

src/sql/pools/pools_pool_id.sql

Fix on top of https://github.com/blockfrost/blockfrost-backend-ryo/pull/142

fix(pools): display non-zero active_stake also for retired pools

---

CHANGELOG.md
src/sql/txs/txs_hash_utxos_1.sql
src/sql/txs/txs_hash_utxos_2.sql

Correct asset is part of normal output. The asset in output collateral
is completely wrong and it should only contain ADA value. This aligns
it with input UTXOs.
Closes https://github.com/blockfrost/blockfrost-backend-ryo/issues/160

fix(sql): don't render asset in collateral utxo output

---

CHANGELOG.md
README.md
src/sql/accounts/accounts_stake_address.sql
src/sql/network/network.sql
src/sql/pools/pools_extended.sql
src/sql/pools/pools_pool_id.sql
src/sql/pools/unpaged/pools_extended.sql

Makes necessary changes to adjust for `instant_reward` (previously MIRs in `reward` table) in all related calls.
Fixed minor bug `live_size` calculation for `/pools/{pool_id}` as previously all pools (even retired) were taken into account, but they should not count toward the `live_size`.

fix(sql): instant_reward (dbsync) adjustment + live_size fix

---

src/sql/pools/pools_pool_id.sql

Remove unnecessary LEFT JOIN when introducing https://github.com/blockfrost/blockfrost-backend-ryo/pull/170

chore(sql): remove leftover left join

---

CHANGELOG.md
src/sql/pools/pools_pool_id.sql

This PR fixes calculation of `live_saturation` in `/pools/{pool_id}`. Although ledger specifies the variable as circulating supply, total supply (`45B - reserves`) is used in this calculation instead.

fix(pools): live saturation calculation

---

CHANGELOG.md
src/sql/pools/pools_pool_id_delegators.sql

Fixes calculation of `live_stake` in `/pools/{pool_id}/delegators` to reflect the split of MIRs into a separate table (`instant_reward`) in new dbsync, which was omitted in 2.0.1 for this endpoint

fix(pools): live stake calculation of delegators with MIRs

---

CHANGELOG.md
src/sql/scripts/scripts.sql
src/sql/scripts/unpaged/scripts.sql

Since there can be multiple scripts with the same `tx_id` it is not enough to order them by this column - change to internal `id` fixes the inconsistency issue.

fix(scripts): ordering (internal id instead of tx_id)

---

CHANGELOG.md
src/sql/addresses/addresses_address.sql
src/sql/addresses/addresses_address_extended.sql

Previously, first queried stake address was displayed. But since tthere can be multiple stake addresses for a given payment_cred, this information was not correct. The fix is to always display `null` instead of a random stake_address.
Testing vector:
http://localhost:3000/addresses/addr_vkh1vt2ntv45rx6e7rfk2qfw2434kdnl0k8fl4h3h6p55d2j6k6czz3
Current state:
```
{
"address": "addr_vkh1vt2ntv45rx6e7rfk2qfw2434kdnl0k8fl4h3h6p55d2j6k6czz3",
"amount": [
{
"unit": "lovelace",
"quantity": "20000000"
}
],
"stake_address": "stake_test1upnhn29zpdwaje5myechf05094s4crp04vnzusqlwg59f4qjx6t73",
"type": "shelley",
"script": false
}
```
This PR:
```
{
"address": "addr_vkh1vt2ntv45rx6e7rfk2qfw2434kdnl0k8fl4h3h6p55d2j6k6czz3",
"amount": [
{
"unit": "lovelace",
"quantity": "20000000"
}
],
"stake_address": …
```

fix(addresses): payment_cred stake_address: null

---

CHANGELOG.md
src/sql/pools/pools_pool_id_metadata.sql
src/sql/txs/txs_hash_pool_updates.sql

Since joining on hash can produce multiple rows in case there were multiple pool registrations using the same metadata (same hash).

fix: off_chain_pool_data join on pmr_id instead of hash

---

CHANGELOG.md
src/sql/pools/pools_pool_id_metadata.sql
src/sql/txs/txs_hash_pool_updates.sql

This reverts commit 7fbc29e57092fe3cc8531760f1f94846cc5ff23b.
"cherry-picks" 4a4ad198db195e8928c2070870e72d815e8d3e5c

Revert "fix: off_chain_pool_data join on pmr_id instead of hash"

---

src/sql/governance/dreps_drep_id_delegators.sql

Instead of using `JOIN` on `txi` and looking for `null txi`, we leverage `consumed_by_tx` enabled by `cardano-db-sync`s [insert option `tx_out.value = "consumed"`](https://github.com/IntersectMBO/cardano-db-sync/blob/08f82fcd942c77a7b1baf28d026713d86f7267fd/doc/configuration.md#value)

feat(governance): optimize UTxO subquery using `consumed_by_tx`

---

.vscode/settings.json
CHANGELOG.md
src/routes/accounts/stake-address/utxos.ts
src/sql/governance/dreps_drep_id_delegators.sql
src/sql/governance/unpaged/dreps_drep_id_delegators.sql

additionally also contains fixes for unpaged SQL for accounts/:stake_addr/utxos and /governance/dreps/:drep_id/delegators

fix: omit unregistered stake addresses from delegators list

---

CHANGELOG.md
src/utils/cost-models-map.ts

based on https://github.com/mkazlauskas/blockfrost-backend-ryo/commit/9e5ea8f60f9701005a022b4f5591a7a06c698797

fix: looser validation for cost model size

---

.eslintrc.cjs
CHANGELOG.md
package.json
src/routes/governance/dreps/drep-id/delegators.ts
src/routes/governance/dreps/drep-id/index.ts
src/routes/governance/dreps/drep-id/metadata.ts
src/routes/governance/dreps/drep-id/updates.ts
src/routes/governance/dreps/drep-id/votes.ts
src/routes/governance/dreps/index.ts
src/routes/governance/proposals/tx-hash/cert-index/votes.ts
src/sql/governance/dreps.sql
src/sql/governance/proposals_proposal_votes.sql
src/sql/governance/unpaged/dreps.sql
src/sql/governance/unpaged/proposals_proposal_votes.sql
src/types/queries/governance.ts
src/utils/governance.ts
src/utils/validation.ts
test/unit/tests/utils/governance.ts
test/unit/tests/utils/validation.ts
yarn-project.nix
yarn.lock

- Support for CIP129 DRep ID - you can query DReps using both legacy format and CIP129 format. The `drep_id` and `hex` fields will reflect the format of the query param
- BREAKING CHANGE: Endpoints `/governance/dreps` and `/governance/proposals/{tx_hash}/{cert_index}/votes` are now using CIP129 format

CIP-0129 drep ids
